-- Dim_Date Table
CREATE TABLE Dim_Date (
    DateKey INT IDENTITY(1,1) PRIMARY KEY,
    RD_NO VARCHAR(50),
    CRASH_DATE VARCHAR(300),
    DATE_POLICE_NOTIFIED VARCHAR(300),
    Date VARCHAR(50),
    Time VARCHAR(50),
    Day INT,
    Month INT,
    Year INT,
    Quarter INT,
    DayOfWeek VARCHAR(200),
    IsWeekend INT
);

-- Dim_Beat Table
CREATE TABLE Dim_Beat (
    BeatKey INT IDENTITY(1,1) PRIMARY KEY,
    RD_NO VARCHAR(50),
    BEAT_OF_OCCURRENCE VARCHAR(300)
);

-- Dim_Cause Table
CREATE TABLE Dim_Cause (
    CauseKey INT IDENTITY(1,1) PRIMARY KEY,
    RD_NO VARCHAR(50),
    PRIM_CONTRIBUTORY_CAUSE VARCHAR(300),
    SEC_CONTRIBUTORY_CAUSE VARCHAR(300),
    DRIVER_ACTION VARCHAR(300),
    DRIVER_VISION VARCHAR(300)
);

-- Dim_Vehicle Table
CREATE TABLE Dim_Vehicle (
    VehicleKey INT IDENTITY(1,1) PRIMARY KEY,
    RD_NO VARCHAR(50),
    VEHICLE_ID INT,
    CRASH_UNIT_ID INT,
    VEHICLE_TYPE VARCHAR(300),
    MAKE VARCHAR(300),
    MODEL VARCHAR(300),
    VEHICLE_YEAR INT,
    LIC_PLATE_STATE VARCHAR(50),
    VEHICLE_DEFECT VARCHAR(300),
    VEHICLE_USE VARCHAR(300),
    OCCUPANT_CNT INT,
    UNIT_TYPE VARCHAR(300),
    TRAVEL_DIRECTION VARCHAR(50),
    UNIT_NO INT,
    MANEUVER VARCHAR(300)
);

-- Dim_Client Table
CREATE TABLE Dim_Client (
    ClientKey INT IDENTITY(1,1) PRIMARY KEY,
    RD_NO VARCHAR(50),
    PERSON_ID VARCHAR(300),
    PERSON_TYPE VARCHAR(300),
    AGE VARCHAR(50),
    SEX VARCHAR(50),
    CITY VARCHAR(300),
    STATE VARCHAR(300),
    INJURY_CLASSIFICATION VARCHAR(300),
    PHYSICAL_CONDITION VARCHAR(300),
    SAFETY_EQUIPMENT VARCHAR(300),
    EJECTION VARCHAR(300),
    AIRBAG_DEPLOYED VARCHAR(300),
    BAC_RESULT VARCHAR(300)
);

-- Dim_Crash Table
CREATE TABLE Dim_Crash (
    CrashKey INT IDENTITY(1,1) PRIMARY KEY,
    RD_NO VARCHAR(50),
    POSTED_SPEED_LIMIT INT,
    TRAFFIC_CONTROL_DEVICE VARCHAR(300),
    DEVICE_CONDITION VARCHAR(300),
    WEATHER_CONDITION VARCHAR(300),
    LIGHTING_CONDITION VARCHAR(300),
    ROADWAY_SURFACE_COND VARCHAR(300),
    FIRST_CRASH_TYPE VARCHAR(300),
    TRAFFICWAY_TYPE VARCHAR(300),
    ALIGNMENT VARCHAR(300),
    STREET_NO INT,
    STREET_NAME VARCHAR(300),
    STREET_DIRECTION VARCHAR(10),
    CRASH_TYPE VARCHAR(300),
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    LOCATION VARCHAR(500),
    ROAD_DEFECT VARCHAR(300),
    FIRST_CONTACT_POINT VARCHAR(300),
    REPORT_TYPE VARCHAR(300)
);

-- Fact_Crash Table
CREATE TABLE Fact_Crash (
    CrashFactKey INT IDENTITY(1,1) PRIMARY KEY,
    RD_NO VARCHAR(50),
    DateKey INT NOT NULL FOREIGN KEY REFERENCES Dim_Date(DateKey),
    BeatKey INT NOT NULL FOREIGN KEY REFERENCES Dim_Beat(BeatKey),
    CauseKey INT NOT NULL FOREIGN KEY REFERENCES Dim_Cause(CauseKey),
    VehicleKey INT NOT NULL FOREIGN KEY REFERENCES Dim_Vehicle(VehicleKey),
    ClientKey INT NOT NULL FOREIGN KEY REFERENCES Dim_Client(ClientKey),
    CrashKey INT NOT NULL FOREIGN KEY REFERENCES Dim_Crash(CrashKey),
    INJURIES_TOTAL FLOAT,
    INJURIES_FATAL FLOAT,
    INJURIES_INCAPACITATING FLOAT,
    INJURIES_REPORTED_NOT_EVIDENT FLOAT,
    NUM_UNITS FLOAT,
    DAMAGE FLOAT,
    DAMAGE_CATEGORY VARCHAR(300),
    INJURIES_NO_INDICATION FLOAT,
    INJURIES_UNKNOWN FLOAT,
    INJURIES_NON_INCAPACITATING FLOAT,
    MOST_SEVERE_INJURY VARCHAR(300)
);

